-- Reverse the initial schema
DROP TABLE IF EXISTS policy_packs CASCADE;
DROP TABLE IF EXISTS coverage_entries CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS approvals CASCADE;
DROP TABLE IF EXISTS findings CASCADE;
DROP TABLE IF EXISTS run_steps CASCADE;
DROP TABLE IF EXISTS runs CASCADE;
DROP TABLE IF EXISTS engagements CASCADE;
DROP TABLE IF EXISTS connector_instances CASCADE;
DROP TABLE IF EXISTS connector_registry CASCADE;
DROP TABLE IF EXISTS assets CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;
