package reporting

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// severity color definitions (R, G, B).
var severityColors = map[string][3]int{
	"critical":      {220, 38, 38},
	"high":          {234, 118, 0},
	"medium":        {202, 170, 0},
	"low":           {37, 99, 235},
	"informational": {120, 120, 120},
}

// RenderPDF generates a professional PDF security validation report.
func RenderPDF(cfg ReportConfig, data *ReportData) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)

	// Title page
	renderTitlePage(pdf, cfg)

	// Content pages
	pdf.AddPage()
	addHeader(pdf)

	switch cfg.Type {
	case ReportExecutive:
		renderPDFExecutive(pdf, data)
	case ReportTechnical:
		renderPDFTechnical(pdf, data)
	case ReportCoverage:
		renderPDFCoverage(pdf, data)
	default:
		renderPDFExecutive(pdf, data)
	}

	// Footer on all pages
	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(128, 128, 128)
		pdf.CellFormat(0, 10,
			fmt.Sprintf("Generated by AegisClaw  |  Page %d/{nb}", pdf.PageNo()),
			"", 0, "C", false, 0, "")
	})
	pdf.AliasNbPages("")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("generating PDF: %w", err)
	}
	if pdf.Err() {
		return nil, fmt.Errorf("generating PDF: %w", pdf.Error())
	}

	return buf.Bytes(), nil
}

func renderTitlePage(pdf *fpdf.Fpdf, cfg ReportConfig) {
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 28)
	pdf.Ln(60)
	pdf.CellFormat(0, 14, "AegisClaw", "", 1, "C", false, 0, "")
	pdf.SetFont("Helvetica", "", 18)
	pdf.CellFormat(0, 12, "Security Validation Report", "", 1, "C", false, 0, "")

	pdf.Ln(20)
	pdf.SetFont("Helvetica", "B", 20)
	pdf.CellFormat(0, 12, cfg.Title, "", 1, "C", false, 0, "")

	pdf.Ln(10)
	pdf.SetFont("Helvetica", "", 14)
	typeLabel := strings.ToUpper(string(cfg.Type[:1])) + string(cfg.Type[1:])
	pdf.CellFormat(0, 10, fmt.Sprintf("Report Type: %s", typeLabel), "", 1, "C", false, 0, "")
	pdf.CellFormat(0, 10, fmt.Sprintf("Generated: %s", time.Now().UTC().Format("2006-01-02 15:04 UTC")), "", 1, "C", false, 0, "")

	// Horizontal rule
	pdf.Ln(20)
	pdf.SetDrawColor(60, 60, 60)
	pdf.SetLineWidth(0.5)
	pdf.Line(30, pdf.GetY(), 180, pdf.GetY())
}

func addHeader(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.CellFormat(0, 8, "AegisClaw Security Validation Report", "", 1, "L", false, 0, "")
	pdf.SetDrawColor(60, 60, 60)
	pdf.SetLineWidth(0.3)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(4)
	pdf.SetTextColor(0, 0, 0)
}

func renderPDFExecutive(pdf *fpdf.Fpdf, data *ReportData) {
	// Section: Executive Summary
	pdfSectionTitle(pdf, "Executive Summary")

	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 7, fmt.Sprintf("Total Assets Under Management: %d", data.TotalAssets), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 7, fmt.Sprintf("Validation Runs Completed: %d", data.CompletedRuns), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 7, fmt.Sprintf("Total Findings: %d", len(data.Findings)), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	// Findings by severity table
	pdfSectionTitle(pdf, "Findings by Severity")
	severities := []string{"critical", "high", "medium", "low", "informational"}

	colWidths := []float64{80, 40}
	// Header row
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(50, 50, 50)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(colWidths[0], 8, "Severity", "1", 0, "C", true, 0, "")
	pdf.CellFormat(colWidths[1], 8, "Count", "1", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)

	for i, sev := range severities {
		if i%2 == 0 {
			pdf.SetFillColor(240, 240, 240)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		c := severityColors[sev]
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(c[0], c[1], c[2])
		pdf.CellFormat(colWidths[0], 7, strings.ToUpper(sev), "1", 0, "L", true, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(0, 0, 0)
		pdf.CellFormat(colWidths[1], 7, fmt.Sprintf("%d", data.FindingsBySev[sev]), "1", 1, "C", true, 0, "")
	}
	pdf.Ln(4)

	// Coverage summary
	pdfSectionTitle(pdf, "Coverage Summary")
	pdf.SetFont("Helvetica", "", 11)
	total := len(data.CoverageEntries)
	gaps := len(data.CoverageGaps)
	pdf.CellFormat(0, 7, fmt.Sprintf("Total Coverage Entries: %d", total), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 7, fmt.Sprintf("Coverage Gaps: %d", gaps), "", 1, "L", false, 0, "")
	if total > 0 {
		pct := float64(total-gaps) / float64(total) * 100
		pdf.CellFormat(0, 7, fmt.Sprintf("Coverage Percentage: %.1f%%", pct), "", 1, "L", false, 0, "")
	}
	pdf.Ln(4)

	// Recommendations
	pdfSectionTitle(pdf, "Recommendations")
	pdf.SetFont("Helvetica", "", 10)
	if data.FindingsBySev["critical"] > 0 {
		pdf.CellFormat(0, 7, "- URGENT: Address critical findings immediately", "", 1, "L", false, 0, "")
	}
	if data.FindingsBySev["high"] > 0 {
		pdf.CellFormat(0, 7, "- Prioritize remediation of high-severity findings", "", 1, "L", false, 0, "")
	}
	if gaps > 0 {
		pdf.CellFormat(0, 7, "- Improve detection coverage for identified gaps", "", 1, "L", false, 0, "")
	}
	pdf.CellFormat(0, 7, "- Continue regular validation runs to maintain security posture", "", 1, "L", false, 0, "")
}

func renderPDFTechnical(pdf *fpdf.Fpdf, data *ReportData) {
	pdfSectionTitle(pdf, "Executive Summary")
	renderPDFSeverityTable(pdf, data)
	pdf.Ln(4)

	// Findings table
	pdfSectionTitle(pdf, "Findings Detail")

	colWidths := []float64{50, 22, 22, 35, 61}
	headers := []string{"Title", "Severity", "Confidence", "Techniques", "Remediation"}

	// Header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(50, 50, 50)
	pdf.SetTextColor(255, 255, 255)
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 8, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)

	pdf.SetFont("Helvetica", "", 8)
	for i, f := range data.Findings {
		if i%2 == 0 {
			pdf.SetFillColor(240, 240, 240)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		title := truncate(f.Title, 30)
		techniques := truncate(strings.Join(f.TechniqueIDs, ", "), 20)
		remediation := ""
		if f.Remediation != nil {
			remediation = truncate(*f.Remediation, 35)
		}

		pdf.CellFormat(colWidths[0], 7, title, "1", 0, "L", true, 0, "")

		// Color-code severity
		c := severityColors[string(f.Severity)]
		pdf.SetTextColor(c[0], c[1], c[2])
		pdf.CellFormat(colWidths[1], 7, string(f.Severity), "1", 0, "C", true, 0, "")
		pdf.SetTextColor(0, 0, 0)

		pdf.CellFormat(colWidths[2], 7, string(f.Confidence), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[3], 7, techniques, "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[4], 7, remediation, "1", 1, "L", true, 0, "")
	}
}

func renderPDFCoverage(pdf *fpdf.Fpdf, data *ReportData) {
	pdfSectionTitle(pdf, "Coverage Matrix")

	colWidths := []float64{55, 40, 40, 40}
	headers := []string{"Technique ID", "Has Telemetry", "Has Detection", "Has Alert"}

	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(50, 50, 50)
	pdf.SetTextColor(255, 255, 255)
	for i, h := range headers {
		pdf.CellFormat(colWidths[i], 8, h, "1", 0, "C", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)

	pdf.SetFont("Helvetica", "", 9)
	for i, e := range data.CoverageEntries {
		if i%2 == 0 {
			pdf.SetFillColor(240, 240, 240)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		pdf.CellFormat(colWidths[0], 7, e.TechniqueID, "1", 0, "L", true, 0, "")
		pdf.CellFormat(colWidths[1], 7, boolLabel(e.HasTelemetry), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[2], 7, boolLabel(e.HasDetection), "1", 0, "C", true, 0, "")
		pdf.CellFormat(colWidths[3], 7, boolLabel(e.HasAlert), "1", 1, "C", true, 0, "")
	}

	if len(data.CoverageGaps) > 0 {
		pdf.Ln(6)
		pdfSectionTitle(pdf, "Coverage Gaps")
		pdf.SetFont("Helvetica", "", 10)
		for _, g := range data.CoverageGaps {
			var missing []string
			if !g.HasTelemetry {
				missing = append(missing, "telemetry")
			}
			if !g.HasDetection {
				missing = append(missing, "detection")
			}
			if !g.HasAlert {
				missing = append(missing, "alert")
			}
			pdf.CellFormat(0, 7,
				fmt.Sprintf("- %s: Missing %s", g.TechniqueID, strings.Join(missing, ", ")),
				"", 1, "L", false, 0, "")
		}
	}
}

func renderPDFSeverityTable(pdf *fpdf.Fpdf, data *ReportData) {
	pdf.SetFont("Helvetica", "", 11)
	pdf.CellFormat(0, 7, fmt.Sprintf("Total Findings: %d    |    Completed Runs: %d", len(data.Findings), data.CompletedRuns), "", 1, "L", false, 0, "")
	pdf.Ln(2)

	colWidths := []float64{80, 40}
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(50, 50, 50)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(colWidths[0], 8, "Severity", "1", 0, "C", true, 0, "")
	pdf.CellFormat(colWidths[1], 8, "Count", "1", 1, "C", true, 0, "")
	pdf.SetTextColor(0, 0, 0)

	for i, sev := range []string{"critical", "high", "medium", "low", "informational"} {
		if i%2 == 0 {
			pdf.SetFillColor(240, 240, 240)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		c := severityColors[sev]
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(c[0], c[1], c[2])
		pdf.CellFormat(colWidths[0], 7, strings.ToUpper(sev), "1", 0, "L", true, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(0, 0, 0)
		pdf.CellFormat(colWidths[1], 7, fmt.Sprintf("%d", data.FindingsBySev[sev]), "1", 1, "C", true, 0, "")
	}
}

func pdfSectionTitle(pdf *fpdf.Fpdf, title string) {
	pdf.SetFont("Helvetica", "B", 14)
	pdf.SetTextColor(30, 30, 30)
	pdf.CellFormat(0, 10, title, "", 1, "L", false, 0, "")
	pdf.SetDrawColor(180, 180, 180)
	pdf.SetLineWidth(0.2)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(3)
	pdf.SetTextColor(0, 0, 0)
}

func boolLabel(v bool) string {
	if v {
		return "Yes"
	}
	return "No"
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
