package agentsdk

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Squad defines the agent squad type.
type Squad string

const (
	SquadGovernance  Squad = "governance"
	SquadEmulation   Squad = "emulation"
	SquadValidation  Squad = "validation"
	SquadImprovement Squad = "improvement"
)

// AgentType identifies specific agents within squads.
type AgentType string

const (
	// Governance Squad
	AgentPolicyEnforcer AgentType = "policy_enforcer"
	AgentApprovalGate   AgentType = "approval_gate"
	AgentReceipt        AgentType = "receipt"

	// Emulation Squad
	AgentPlanner  AgentType = "planner"
	AgentExecutor AgentType = "executor"
	AgentEvidence AgentType = "evidence"

	// Validation Squad
	AgentTelemetryVerifier  AgentType = "telemetry_verifier"
	AgentDetectionEvaluator AgentType = "detection_evaluator"
	AgentResponseAutomator  AgentType = "response_automator"

	// Improvement Squad
	AgentCoverageMapper AgentType = "coverage_mapper"
	AgentRegression     AgentType = "regression"
	AgentDrift          AgentType = "drift"
)

// Agent is the interface all agents must implement.
type Agent interface {
	Name() AgentType
	Squad() Squad
	Init(ctx context.Context, deps AgentDeps) error
	HandleTask(ctx context.Context, task *Task) (*Result, error)
	Shutdown(ctx context.Context) error
}

// AgentDeps holds dependencies injected into agents.
// Fields are typed as `any` to avoid circular imports between the public SDK
// package and internal packages. Agents type-assert in their Init() methods.
type AgentDeps struct {
	Logger           any // *slog.Logger
	DB               any // *pgxpool.Pool
	NATSClient       any // *nats.Client
	EvidenceStore    any // *evidence.Store
	PolicyEngine     any // *policy.Engine
	OllamaBridge     any // ollama client
	ConnectorSvc          any // *connector.Service
	PlaybookLoader        any // *playbook.Loader
	PlaybookExecutor      any // *playbook.Executor
	ReceiptHMACKey        any // []byte - HMAC key for receipt signing
	ConnectorInstanceRepo any // *repository.ConnectorInstanceRepo
}

// Task is a unit of work dispatched to an agent.
type Task struct {
	ID            string          `json:"id"`
	RunID         uuid.UUID       `json:"run_id"`
	EngagementID  uuid.UUID       `json:"engagement_id"`
	OrgID         uuid.UUID       `json:"org_id"`
	StepNumber    int             `json:"step_number"`
	Action        string          `json:"action"`
	Tier          int             `json:"tier"`
	Inputs        json.RawMessage `json:"inputs"`
	PolicyContext *PolicyContext   `json:"policy_context,omitempty"`
	CreatedAt     time.Time       `json:"created_at"`
}

// PolicyContext provides policy information for the task.
type PolicyContext struct {
	AllowedTiers     []int       `json:"allowed_tiers"`
	TargetAllowlist  []uuid.UUID `json:"target_allowlist"`
	TargetExclusions []uuid.UUID `json:"target_exclusions"`
	RateLimit        int         `json:"rate_limit"`
	ConcurrencyCap   int         `json:"concurrency_cap"`
}

// ResultStatus defines the outcome of a task.
type ResultStatus string

const (
	StatusCompleted     ResultStatus = "completed"
	StatusFailed        ResultStatus = "failed"
	StatusBlocked       ResultStatus = "blocked"
	StatusNeedsApproval ResultStatus = "needs_approval"
)

// Result is the outcome of an agent processing a task.
type Result struct {
	TaskID      string          `json:"task_id"`
	Status      ResultStatus    `json:"status"`
	Outputs     json.RawMessage `json:"outputs,omitempty"`
	EvidenceIDs []string        `json:"evidence_ids,omitempty"`
	Findings    []FindingOutput `json:"findings,omitempty"`
	NextSteps   []Task          `json:"next_steps,omitempty"`
	CleanupDone bool            `json:"cleanup_done"`
	Error       string          `json:"error,omitempty"`
	CompletedAt time.Time       `json:"completed_at"`
}

// FindingOutput is a finding generated by an agent.
type FindingOutput struct {
	Title          string   `json:"title"`
	Description    string   `json:"description,omitempty"`
	Severity       string   `json:"severity"`
	Confidence     string   `json:"confidence"`
	AffectedAssets []string `json:"affected_assets,omitempty"`
	TechniqueIDs   []string `json:"technique_ids,omitempty"`
	EvidenceIDs    []string `json:"evidence_ids,omitempty"`
	Remediation    string   `json:"remediation,omitempty"`
}

// ApprovalRequest is sent when an agent needs human approval.
type ApprovalRequest struct {
	ID          string    `json:"id"`
	TaskID      string    `json:"task_id"`
	RunID       uuid.UUID `json:"run_id"`
	OrgID       uuid.UUID `json:"org_id"`
	AgentType   AgentType `json:"agent_type"`
	Description string    `json:"description"`
	Tier        int       `json:"tier"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
}

// ApprovalDecision is the human response to an approval request.
type ApprovalDecision struct {
	RequestID string `json:"request_id"`
	Approved  bool   `json:"approved"`
	Rationale string `json:"rationale,omitempty"`
	DecidedBy string `json:"decided_by"`
	DecidedAt time.Time `json:"decided_at"`
}
